### PR TITLE
gpla_e.m: initialize the cell array ind2depo, which may be in the env…

### PR DESCRIPTION
**Pull request by mkarikom**
…ironment from Mathworks' Wavelet Toolbox so that update "ind2depo{i}" on line 2133 doesn't crash the script

### CODE REVIEW

**Comment by mkarikom** [comment]
this seems to fix the bug where demos crash if the default laplace likelihood approx is used

**Comment by avehtari** [comment]
Thanks for the pull request. Could you provide more details on the commit 4bc3e26 ?

I changed the pull request to be targeted for the develop branch.

**Comment by mkarikom** [comment]
Hi, Apologies, I should have only submitted a pull-request for commit
bbd54d0
<https://github.com/gpstuff-dev/gpstuff/pull/50/commits/bbd54d0eb7657f28126b2c1b75aa7e7a77a3e39d>
.

Commit 4bc3e26
<https://github.com/gpstuff-dev/gpstuff/commit/4bc3e260ae02048d68b978541947ffbac62af162>
was just a temporary fix in my fork until I could figure out why line 107
in demo_survival_aft.m
<https://github.com/gpstuff-dev/gpstuff/blob/develop/gp/demo_survival_aft.m>
:

> [pmu,~,xtc]=gp_cpred(gpia, x, y, x, [i1 i2], 'z', ye, 'target','mu');
>
returns normalized posterior predictive mean and quantiles for the surv
time that appear to be all ones, vs Laplace which seems more reasonable.
Please see attached for plot examples.
Thanks, Matt

**Comment by jpvanhat** [comment]
Hi Mat. Could you change your pull request so that it includes only commit bbd54d0? This is good fix and should be done. If not we can do it ourselves as well.

... and target the pull request to "develop" branch.

**Comment by mkarikom** [comment]
No problem, I just ended up re-forking the dev branch and submitted a new
pr with just the one line in gpla_e.  Thanks

**Comment by jpvanhat** [comment]
Thank you Mat. I just accepted your new pr and will close this now.

**Pull request closed without merging**
